---
# Create MetalLB Service
apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - name: sql
    port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: cockroachdb
    app.kubernetes.io/name: cockroachdb
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.129.2