apiVersion: v1
kind: Service
metadata:
  name: seafile
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: seafile
subsets:
  - addresses:
      - ip: 192.168.128.104
    ports:
      - port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: seafhttp
spec:
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Endpoints
metadata:
  name: seafhttp
subsets:
  - addresses:
      - ip: 192.168.128.104
    ports:
      - port: 8082
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seafile
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-header: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Forwarded-Host $server_name;      
    # nginx.ingress.kubernetes.io/server-snippet: |
    #   proxy_set_header   Host $host;
    #   proxy_set_header   X-Real-IP $remote_addr;
    #   proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    #   proxy_set_header   X-Forwarded-Host $server_name;
    #   proxy_connect_timeout  36000s;
    #   proxy_read_timeout  36000s;
    #   proxy_send_timeout  36000s;
    #   send_timeout  36000s;
    #   client_max_body_size 0;
spec:
  rules:
  - host: seafile.home.frontenac.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: seafile
            port: 
              number: 8000
      - path: /seafhttp
        pathType: Prefix
        backend:
          service:
            name: seafhttp
            port: 
              number: 8082
  tls:
  - hosts:
    - seafile.home.frontenac.tech
    secretName: seafile.home.frontenac.tech